data_path: '/Users/dustin/Documents/School/1_stanford/classes/cs224n/project/data/natural-instructions/tasks/' #task001_quoref_question_generation.json
model_name: 'all-mpnet-base-v2' #'all-MiniLM-L6-v2'
load_embeddings: True
embedding_path: '/Users/dustin/Documents/School/1_stanford/classes/cs224n/project/cs224n-project/src/semantic_similarity/embeddings_mpnet_cat-def-exam.json'
embedding_aggregation: 'mean' # could be 'mean' or other values
clustering_method: 'kmeans'
use_elbow_method: True
num_clusters: 
  - 42
distance_threshold: 